### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by El-Abbady** [Github2k10/Safar#22]
Great Job...
" after changing the database configuration , the backend api works fine ( testing it from postman )"
but I can't access the "localhost:8080/" Whitelabel Error Page
and how can I access the home page ( frontend )

Thanks You in Advance

**Comment by ez-ankit** [comment]
This is only a backend project, so there is no Frontend Part. but you can visit "http://localhost:8080/swagger-ui/index.html" to have a frontend to access all the API.

I am happy to see you if you can collaborate to work on the frontend part...

Don't forget to give a like to the repo.

Regards
