### ISSUE TITLE
Accesing fields 

### ISSUE THREAD

**Issue by PushpitSB** [Github2k10/Safar#23]
I just cloned the repository and looks like the code was giving errors as it had no way of accessing the private fields, is there something I am doing wrong as I manually added getters and setters and then started running this app and I get these errors 
![Screenshot 2024-06-17 at 7 33 07 PM](https://github.com/Github2k10/Safar/assets/118074739/ee4a7cad-c44e-4b52-810c-272d4c2aed05)
![Screenshot 2024-06-17 at 7 33 07 PM](https://github.com/Github2k10/Safar/assets/118074739/ee4a7cad-c44e-4b52-810c-272d4c2aed05)
![Screenshot 2024-06-17 at 7 33 07 PM](https://github.com/Github2k10/Safar/assets/118074739/ee4a7cad-c44e-4b52-810c-272d4c2aed05)

**Comment by ez-ankit** [comment]
I think, the error occurred due to the MySQL connection. Please try to check MySQL password, username, and host.
